apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "client.fullname" . }}-otel-collector
  name: {{ include "client.fullname" . }}-otel-collector
spec:
  ports:
  - port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app: {{ include "client.fullname" . }}-otel-collector
