dist:
  name: kubviz-otel-collector
  description: KubViz OTel Collector distribution
  output_path: _build
  otelcol_version: 0.108.1

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.108.1
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.108.1
  - gomod:
      github.com/intelops/kubviz/pkg/opentelemetry/exporters/natsexporter v0.0.0-local

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.108.1

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.108.1

replaces:
  - github.com/intelops/kubviz/pkg/opentelemetry/exporters/natsexporter => ../../pkg/opentelemetry/exporters/natsexporter
